Hoe te gebruiken:
Gebruik voor deze applicatie de IDE Intellij IDEA. Deze is te downloaden van deze link: https://www.jetbrains.com/idea/download/
Ook heb je de nieuwste java JDK nodig, versie 19, die te downloaden is van java's website

Vervolgens kloon je deze repository naar Intellij en open je het project. 
Je wilt alleen de complete folder openen.

Als je het project voor het eerst opent, moet hij waarschijnlijk eerst alles laden en indexen, dus dat kan even duren.
Als dit vervolgens klaar is kan je de applicatie starten.
Dit doe je door de volgende volders te openen:
src/main/java/com.example.uploadingfiles
Vervolgens kan je de class UploadingFIlesApplication openen en dan daarmee de applicatie starten.

Als de applicatie is gestart, en dat weet je door als er in de console iets staat als "Started UploadingFilesApplication in 1.421 seconds (JVM running for 1.718)",
ga dan naar localhost:8080 via een webbrowser om bestanden te uploaden.

Mocht er onderweg iets mis gaan en je komt er zelf niet uit, kan je mij een berichtje sturen en ik zal kijken wat er mis is gegaan in mijn uitleg.

=================================================================================================================

